- hosts: vault

  pre_tasks:
  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    become: true

  roles:
  - role: ansible-consul
    tags:
      - install_consul
    become: true
